--- 
kind: pipeline
name: default
platform: 
  arch: amd64
  os: linux
steps: 
  - 
    commands: 
      - "chmod -R 777 /tmp"
      - "docker run --rm --add-host fortidevsec.forticloud.com:10.34.160.80 --mount type=bind,source=\"$PWD\",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest"
    name: SAST
type: exec
