version: 2.1

jobs:
    SAST:
        machine: yes
        steps:
          - checkout
          - run: docker run --rm --add-host fortidevsec.forticloud.com:10.34.160.80 --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest

workflows:
    Scans:
        jobs:
          - SAST
